---
title: "R Notebook"
output: html_notebook
---

```{r loading data}
options(java.parameters = "-Xmx32000m")
options(scipen = 999)
pacman::p_load(stringr,tidyverse,RJDBC,sqldf,dplyr,splitstackshape,svMisc,data.table,googlesheets4,openxlsx)

#functions
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
paste3 <- function(...,sep="",collapse=NULL) {
   L <- list(...)
   L <- lapply(L,function(x) {x[is.na(x)] <- ""; x})
   ret <-gsub(paste0("(^",sep,"|",sep,"$)"),"",
               gsub(paste0(sep,sep),sep,
                    do.call(paste,c(L,list(sep=sep)))))
   is.na(ret) <- ret==""
   trim(ret)
}
`%notin%` <- Negate(`%in%`)

#downloading files
bn_books <- read.csv2("C:/Users/Cezary/Downloads/pw_ksiazki.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 
bn_articles <- read.csv2("C:/Users/Cezary/Downloads/pw_czasopisma.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 
cz_books <- read.csv2("C:/Users/Cezary/Downloads/cz_pw_file_1.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 
cz_articles <- read.csv2("C:/Users/Cezary/Downloads/cz_pw_file_2.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 

#connecting to PBL database
jdbcDriver = JDBC("oracle.jdbc.OracleDriver",classPath="C:/Users/Cezary/Downloads/ojdbc6.jar")
PBL <- dbConnect(jdbcDriver, "jdbc:oracle:thin:@//pbl.ibl.poznan.pl:1521/xe", "IBL_SELECT", "CR333444")
pbl_articles1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                          z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_articles2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                            tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                            z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_articles3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_articles4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_articles <- sqldf("select *
              from pbl_articles1 a
              UNION
              select *
              from pbl_articles2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_articles1 a)")
pbl_articles <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select * 
                      from pbl_articles3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles a)")
pbl_articles <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select *
                      from pbl_articles4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles a)")
pbl_articles1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                          z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_articles2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                            to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                            z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_articles3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_articles4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_articles1 <- sqldf("select *
              from pbl_articles1 a
              UNION
              select *
              from pbl_articles2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_articles1 a)")
pbl_articles1 <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select * 
                      from pbl_articles3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles1 a)")
pbl_articles1 <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select *
                      from pbl_articles4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles1 a)")
pbl_articles <- sqldf("select *
              from pbl_articles a
              UNION
              select *
              from pbl_articles1 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_articles a)")

hasla_przekrojowe <- dbGetQuery(PBL,
                                "select hpz.hz_za_zapis_id,hp.hp_nazwa,khp.kh_nazwa
                                from IBL_OWNER.pbl_hasla_przekrojowe hp
                                join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_klucze_hasla_przekr khp on khp.kh_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_hasla_zapisow_klucze hzk on hzk.hzkh_hz_hp_haslo_id=hp.hp_haslo_id and hzk.hzkh_kh_klucz_id=khp.kh_klucz_id and hzk.hzkh_hz_za_zapis_id=hpz.hz_za_zapis_id")

hasla_przekrojowe2 <- dbGetQuery(PBL,
                                 "select hpz.hz_za_zapis_id,hp.hp_nazwa,to_char(null) \"KH_NAZWA\"
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id")

hasla_przekrojowe <- sqldf("select *
              from hasla_przekrojowe a
              UNION
              select *
              from hasla_przekrojowe2 b
              where b.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA not in (select a.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA
              from hasla_przekrojowe a)")

indeks_osobowy <- dbGetQuery(PBL,
                             "select odi_za_zapis_id, odi_nazwisko, odi_imie
                              from IBL_OWNER.pbl_osoby_do_indeksu")

pbl_articles <- merge(pbl_articles,indeks_osobowy,by.x = "rekord_id",by.y = "ODI_ZA_ZAPIS_ID", all.x = TRUE)
pbl_articles <- merge(pbl_articles,hasla_przekrojowe,by.x = "rekord_id", by.y = "HZ_ZA_ZAPIS_ID", all.x = TRUE)

#write.csv2(pbl_articles, "C:/Users/Cezary/Downloads/pbl_articles.csv", row.names = F, na = '', fileEncoding = 'Windows-1250')

pbl_books1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_books2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                            tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						  join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_books3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok  
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_books4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok 
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_books <- sqldf("select *
              from pbl_books1 a
              UNION
              select *
              from pbl_books2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books1 a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select * 
                      from pbl_books3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_books2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                            to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						  join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_books3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_books4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok                               
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_books1 <- sqldf("select *
              from pbl_books1 a
              UNION
              select *
              from pbl_books2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select * 
                      from pbl_books3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books <- sqldf("select *
              from pbl_books a
              UNION
              select *
              from pbl_books1 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books a)")

hasla_przekrojowe <- dbGetQuery(PBL,
                                "select hpz.hz_za_zapis_id,hp.hp_nazwa,khp.kh_nazwa
                                from IBL_OWNER.pbl_hasla_przekrojowe hp
                                join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_klucze_hasla_przekr khp on khp.kh_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_hasla_zapisow_klucze hzk on hzk.hzkh_hz_hp_haslo_id=hp.hp_haslo_id and hzk.hzkh_kh_klucz_id=khp.kh_klucz_id and hzk.hzkh_hz_za_zapis_id=hpz.hz_za_zapis_id")

hasla_przekrojowe2 <- dbGetQuery(PBL,
                                 "select hpz.hz_za_zapis_id,hp.hp_nazwa,to_char(null) \"KH_NAZWA\"
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id")

hasla_przekrojowe <- sqldf("select *
              from hasla_przekrojowe a
              UNION
              select *
              from hasla_przekrojowe2 b
              where b.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA not in (select a.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA
              from hasla_przekrojowe a)")

indeks_osobowy <- dbGetQuery(PBL,
                             "select odi_za_zapis_id, odi_nazwisko, odi_imie
                              from IBL_OWNER.pbl_osoby_do_indeksu")

pbl_books <- merge(pbl_books,indeks_osobowy,by.x = "rekord_id",by.y = "ODI_ZA_ZAPIS_ID", all.x = TRUE)
pbl_books <- merge(pbl_books,hasla_przekrojowe,by.x = "rekord_id", by.y = "HZ_ZA_ZAPIS_ID", all.x = TRUE)

pbl_serie <- dbGetQuery(PBL,
                        "select z.za_zapis_id,z.za_seria_wydawnicza
                        from pbl_zapisy z
                        where z.za_type like 'KS'")
pbl_books <- merge(pbl_books,pbl_serie,by.x = "rekord_id", by.y = "ZA_ZAPIS_ID", all.x = TRUE)

#write.csv2(pbl_books, "C:/Users/Cezary/Downloads/pbl_books.csv", row.names = F, na = '', fileEncoding = 'Windows-1250')
```

```{r extracting personal data}
#bn_books
#field X100
marc_field_bnb_100 <- bn_books %>%
  select(id,X100)%>%
  filter(X100!="") %>%
  cSplit(.,"X100",sep = "|",direction = "long") %>%
  filter(X100!="")
subfield_list<- str_extract_all(bn_books$X100,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_bnb_100)[1]))
colnames(empty_table) <-subfield_list
marc_field_bnb_100<-cbind(marc_field_bnb_100,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field_bnb_100$X100 <- str_replace(marc_field_bnb_100$X100,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_bnb_100[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field_bnb_100$X100),str_replace_all(gsub(string,"\\3",marc_field_bnb_100$X100),"\\%.", "~"),NA)
}

marc_field_bnb_100$`%1` <- trim(marc_field_bnb_100$`%1`)
marc_field_bnb_100$`%2` <- trim(marc_field_bnb_100$`%2`)
marc_field_bnb_100$`%d` <- trim(marc_field_bnb_100$`%d`)
marc_field_bnb_100$`%4` <- trim(marc_field_bnb_100$`%4`)
marc_field_bnb_100$`%3` <- trim(marc_field_bnb_100$`%3`)
marc_field_bnb_100$`%s` <- trim(marc_field_bnb_100$`%s`)
marc_field_bnb_100$`%w` <- trim(marc_field_bnb_100$`%w`)
marc_field_bnb_100$`%r` <- trim(marc_field_bnb_100$`%r`)
marc_field_bnb_100$`%m` <- trim(marc_field_bnb_100$`%m`)
marc_field_bnb_100$`%p` <- trim(marc_field_bnb_100$`%p`)
marc_field_bnb_100$`%k` <- trim(marc_field_bnb_100$`%k`)
marc_field_bnb_100$field <- "X100"

bn_record_people_X100 <- marc_field_bnb_100 %>%
  select(record_id = id, `%1`, `%2`, `%d`, `%4`, `%3`, `%s`,`%w`,`%p`,`%k`) %>%
  mutate(`%1` = paste(`%1`,`%3`,sep = " ")) %>%
  mutate(`%2` = paste(`%2`,`%4`,sep = " ")) %>%
  select(-`%3`,-`%4`) %>%
  mutate(data_set = "bn_books", field = "X100") %>%
  select(data_set, field, 1:8)
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern=' NA', replacement='')
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern='NANA', replacement='')
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern='NA$', replacement='')
bn_record_people_X100$name <- paste(bn_record_people_X100$`%1`,bn_record_people_X100$`%2`,bn_record_people_X100$`%d`,sep = "|")
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern='\\|NA', replacement='')
#field X700
marc_field_bnb_700 <- bn_books %>%
  select(id,X700)%>%
  filter(X700!="") %>%
  cSplit(.,"X700",sep = "|",direction = "long") %>%
  filter(X700!="")
subfield_list<- str_extract_all(bn_books$X700,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_bnb_700)[1]))
colnames(empty_table) <-subfield_list
marc_field_bnb_700<-cbind(marc_field_bnb_700,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field_bnb_700$X700 <- str_replace(marc_field_bnb_700$X700,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_bnb_700[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field_bnb_700$X700),str_replace_all(gsub(string,"\\3",marc_field_bnb_700$X700),"\\%.", "~"),NA)
}

marc_field_bnb_700$`%1` <- trim(marc_field_bnb_700$`%1`)
marc_field_bnb_700$`%2` <- trim(marc_field_bnb_700$`%2`)
marc_field_bnb_700$`%d` <- trim(marc_field_bnb_700$`%d`)
marc_field_bnb_700$`%4` <- trim(marc_field_bnb_700$`%4`)
marc_field_bnb_700$`%3` <- trim(marc_field_bnb_700$`%3`)
marc_field_bnb_700$`%s` <- trim(marc_field_bnb_700$`%s`)
marc_field_bnb_700$`%w` <- trim(marc_field_bnb_700$`%w`)
marc_field_bnb_700$`%r` <- trim(marc_field_bnb_700$`%r`)
marc_field_bnb_700$`%m` <- trim(marc_field_bnb_700$`%m`)
marc_field_bnb_700$`%p` <- trim(marc_field_bnb_700$`%p`)
marc_field_bnb_700$`%k` <- trim(marc_field_bnb_700$`%k`)
marc_field_bnb_700$field <- "X700"

bn_record_people_X700 <- marc_field_bnb_700 %>%
  select(record_id = id, `%1`, `%2`, `%d`, `%4`, `%3`, `%s`,`%w`,`%p`,`%k`) %>%
  mutate(`%1` = paste(`%1`,`%3`,sep = " ")) %>%
  mutate(`%2` = paste(`%2`,`%4`,sep = " ")) %>%
  select(-`%3`,-`%4`) %>%
  mutate(data_set = "bn_books", field = "X700") %>%
  select(data_set, field, 1:8)
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern=' NA', replacement='')
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern='NANA', replacement='')
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern='NA$', replacement='')
bn_record_people_X700$name <- paste(bn_record_people_X700$`%1`,bn_record_people_X700$`%2`,bn_record_people_X700$`%d`,sep = "|")
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern='\\|NA', replacement='')
#field X701
marc_field_bnb_701 <- bn_books %>%
  select(id,X701)%>%
  filter(X701!="") %>%
  cSplit(.,"X701",sep = "|",direction = "long") %>%
  filter(X701!="")
subfield_list<- str_extract_all(bn_books$X701,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_bnb_701)[1]))
colnames(empty_table) <-subfield_list
marc_field_bnb_701<-cbind(marc_field_bnb_701,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field_bnb_701$X701 <- str_replace(marc_field_bnb_701$X701,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_bnb_701[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field_bnb_701$X701),str_replace_all(gsub(string,"\\3",marc_field_bnb_701$X701),"\\%.", "~"),NA)
}

marc_field_bnb_701$`%1` <- trim(marc_field_bnb_701$`%1`)
marc_field_bnb_701$`%2` <- trim(marc_field_bnb_701$`%2`)
marc_field_bnb_701$`%d` <- trim(marc_field_bnb_701$`%d`)
marc_field_bnb_701$`%3` <- trim(marc_field_bnb_701$`%3`)
marc_field_bnb_701$`%s` <- trim(marc_field_bnb_701$`%s`)
marc_field_bnb_701$`%r` <- trim(marc_field_bnb_701$`%r`)
marc_field_bnb_701$`%p` <- trim(marc_field_bnb_701$`%p`)
marc_field_bnb_701$field <- "X701"

bn_record_people_X701 <- marc_field_bnb_701 %>%
  select(record_id = id, `%1`, `%2`, `%d`, `%3`, `%s`, `%p`) %>%
  mutate(`%4` = NA, `%w` = NA, `%k` = NA) %>%
  mutate(`%1` = paste(`%1`,`%3`,sep = " ")) %>%
  mutate(`%2` = paste(`%2`,`%4`,sep = " ")) %>%
  select(-`%3`,-`%4`) %>%
  mutate(data_set = "bn_books", field = "X701") %>%
  select(colnames(bn_record_people_X100)[1:10])
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern=' NA', replacement='')
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern='NANA', replacement='')
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern='NA$', replacement='')
bn_record_people_X701$name <- paste(bn_record_people_X701$`%1`,bn_record_people_X701$`%2`,bn_record_people_X701$`%d`,sep = "|")
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern='\\|NA', replacement='')

#concatenate bn

bn_record_people <- rbind(bn_record_people_X100,bn_record_people_X700,bn_record_people_X701) 
bn_record_people <- bn_record_people %>%
  mutate(id_osoby = paste("bnb",seq.int(nrow(bn_record_people)),sep = ""))

names_of_columns <- colnames(bn_record_people)

set1 <- bn_record_people %>%
  select(1:6,11:12) %>%
  mutate(`%1` = paste(`%1`,`%2`,`%d`, sep = " ")) %>% 
  select(data_set,field,record_id,`%1`,name,id_osoby)
set1 <- set1 %>%
  mutate(subfield = colnames(set1)[4])
colnames(set1)[4] <- "name_form"
set1[] <- lapply(set1, gsub, pattern=' NA', replacement='')
set1$name_form <- trim(set1$name_form)

set2 <- bn_record_people[c(1:3,7,11:12)] %>%
  filter(!is.na(`%s`))
set2 <- set2 %>%
  mutate(subfield = colnames(set2)[4])
colnames(set2)[4] <- "name_form"
set3 <- bn_record_people[c(1:3,8,11:12)] %>%
  filter(!is.na(`%w`))
set3 <- set3 %>%
  mutate(subfield = colnames(set3)[4])
colnames(set3)[4] <- "name_form"
set4 <- bn_record_people[c(1:3,9,11:12)] %>%
  filter(!is.na(`%p`))
set4 <- set4 %>%
  mutate(subfield = colnames(set4)[4])
colnames(set4)[4] <- "name_form"
set5 <- bn_record_people[c(1:3,10,11:12)] %>%
  filter(!is.na(`%k`))
set5 <- set5 %>%
  mutate(subfield = colnames(set5)[4])
colnames(set5)[4] <- "name_form"

bn_record_people <- rbind(set1,set2,set3,set4,set5)
bn_record_people <- bn_record_people %>%
  select(data_set,record_id,field,subfield,id_osoby,name_form,id_osoby) %>%
  mutate(name_form_id = paste(data_set,record_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", ""))

#cz_books
#field X100
marc_field_czb_100 <- cz_books %>%
  select(id,X100)%>%
  filter(X100!="") %>%
  cSplit(.,"X100",sep = "|",direction = "long") %>%
  filter(X100!="")
marc_field_czb_100 <- mutate(marc_field_czb_100,
               indicator = str_replace_all(marc_field_czb_100$X100,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X100,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_czb_100)[1]))
colnames(empty_table) <-subfield_list
marc_field_czb_100<-cbind(marc_field_czb_100,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field_czb_100$X100 <- str_replace(marc_field_czb_100$X100,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_czb_100[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_czb_100$X100),str_replace_all(gsub(string,"\\3",marc_field_czb_100$X100),"\\${2}.", "~"),NA)
}

marc_field_czb_100$`$$a` <- trim(marc_field_czb_100$`$$a`)
marc_field_czb_100$`$$d` <- trim(marc_field_czb_100$`$$d`)
marc_field_czb_100$`$$b` <- str_remove(trim(marc_field_czb_100$`$$b`),"\\.$")
marc_field_czb_100$field <- "X100"

cz_record_people_X100 <- marc_field_czb_100 %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_books", field = "X100") %>%
  select(data_set, field,1:4)
cz_record_people_X100[] <- lapply(cz_record_people_X100, gsub, pattern=' NA', replacement='')
cz_record_people_X100[] <- lapply(cz_record_people_X100, gsub, pattern='\\|NA', replacement='')

#field X600
marc_field_czb_600 <- cz_books %>%
  select(id,X600)%>%
  filter(X600!="") %>%
  cSplit(.,"X600",sep = "|",direction = "long") %>%
  filter(X600!="")
marc_field_czb_600 <- mutate(marc_field_czb_600,
               indicator = str_replace_all(marc_field_czb_600$X600,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X600,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_czb_600)[1]))
colnames(empty_table) <-subfield_list
marc_field_czb_600<-cbind(marc_field_czb_600,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field_czb_600$X600 <- str_replace(marc_field_czb_600$X600,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_czb_600[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_czb_600$X600),str_replace_all(gsub(string,"\\3",marc_field_czb_600$X600),"\\${2}.", "~"),NA)
}

marc_field_czb_600$`$$a` <- trim(marc_field_czb_600$`$$a`)
marc_field_czb_600$`$$d` <- trim(marc_field_czb_600$`$$d`)
marc_field_czb_600$`$$b` <- str_remove(trim(marc_field_czb_600$`$$b`),"\\.$")
marc_field_czb_600$field <- "X600"

cz_record_people_X600 <- marc_field_czb_600 %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_books", field = "X600") %>%
  select(data_set, field,1:4)
cz_record_people_X600[] <- lapply(cz_record_people_X600, gsub, pattern=' NA', replacement='')
cz_record_people_X600[] <- lapply(cz_record_people_X600, gsub, pattern='\\|NA', replacement='')

#field X700
marc_field_czb_700 <- cz_books %>%
  select(id,X700)%>%
  filter(X700!="") %>%
  cSplit(.,"X700",sep = "|",direction = "long") %>%
  filter(X700!="")
marc_field_czb_700 <- mutate(marc_field_czb_700,
               indicator = str_replace_all(marc_field_czb_700$X700,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X700,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_czb_700)[1]))
colnames(empty_table) <-subfield_list
marc_field_czb_700<-cbind(marc_field_czb_700,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field_czb_700$X700 <- str_replace(marc_field_czb_700$X700,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_czb_700[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_czb_700$X700),str_replace_all(gsub(string,"\\3",marc_field_czb_700$X700),"\\${2}.", "~"),NA)
}

marc_field_czb_700$`$$a` <- trim(marc_field_czb_700$`$$a`)
marc_field_czb_700$`$$d` <- trim(marc_field_czb_700$`$$d`)
marc_field_czb_700$`$$b` <- str_remove(trim(marc_field_czb_700$`$$b`),"\\.$")
marc_field_czb_700$field <- "X700"

cz_record_people_X700 <- marc_field_czb_700 %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_books", field = "X700") %>%
  select(data_set, field,1:4)
cz_record_people_X700[] <- lapply(cz_record_people_X700, gsub, pattern=' NA', replacement='')
cz_record_people_X700[] <- lapply(cz_record_people_X700, gsub, pattern='\\|NA', replacement='')

#concatenate all cz books
cz_record_people <- rbind(cz_record_people_X100,cz_record_people_X600,cz_record_people_X700)
cz_record_people <- cz_record_people %>%
  mutate(id_osoby = paste("czb",seq.int(nrow(cz_record_people)),sep = ""))
names_of_columns <- colnames(cz_record_people)


cz_record_people <- cz_record_people %>%
  select(names_of_columns,id_osoby) %>%
  arrange(field,as.integer(record_id))
cz_record_people <- cz_record_people %>%
  mutate(name_form = paste(`$$a`, `$$d`, sep = " ")) %>% 
  select(data_set,field,record_id,name_form,name,id_osoby)
cz_record_people <- cz_record_people %>%
  mutate(subfield = "$$a")
cz_record_people[] <- lapply(cz_record_people, gsub, pattern=' NA', replacement='')
cz_record_people$name_form <- trim(cz_record_people$name_form)
cz_record_people <- cz_record_people %>%
  select(data_set,record_id,field,subfield,id_osoby,name_form) %>%
  mutate(name_form_id = paste(data_set,record_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", ""))

#cz_articles
#field X100
marc_field_cza_100 <- cz_articles %>%
  select(id,X100)%>%
  filter(X100!="") %>%
  cSplit(.,"X100",sep = "|",direction = "long") %>%
  filter(X100!="")
marc_field_cza_100 <- mutate(marc_field_cza_100,
               indicator = str_replace_all(marc_field_cza_100$X100,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X100,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_cza_100)[1]))
colnames(empty_table) <-subfield_list
marc_field_cza_100<-cbind(marc_field_cza_100,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field_cza_100$X100 <- str_replace(marc_field_cza_100$X100,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_cza_100[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_cza_100$X100),str_replace_all(gsub(string,"\\3",marc_field_cza_100$X100),"\\${2}.", "~"),NA)
}

marc_field_cza_100$`$$a` <- trim(marc_field_cza_100$`$$a`)
marc_field_cza_100$`$$d` <- trim(marc_field_cza_100$`$$d`)
marc_field_cza_100$`$$b` <- str_remove(trim(marc_field_cza_100$`$$b`),"\\.$")
marc_field_cza_100$field <- "X100"

cz_record_people_art_X100 <- marc_field_cza_100 %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_articles", field = "X100") %>%
  select(data_set, field,1:4)
cz_record_people_art_X100[] <- lapply(cz_record_people_art_X100, gsub, pattern=' NA', replacement='')
cz_record_people_art_X100[] <- lapply(cz_record_people_art_X100, gsub, pattern='\\|NA', replacement='')

#field X600
marc_field_cza_600 <- cz_articles %>%
  select(id,X600)%>%
  filter(X600!="") %>%
  cSplit(.,"X600",sep = "|",direction = "long") %>%
  filter(X600!="")
marc_field_cza_600 <- mutate(marc_field_cza_600,
               indicator = str_replace_all(marc_field_cza_600$X600,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X600,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_cza_600)[1]))
colnames(empty_table) <-subfield_list
marc_field_cza_600<-cbind(marc_field_cza_600,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field_cza_600$X600 <- str_replace(marc_field_cza_600$X600,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_cza_600[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_cza_600$X600),str_replace_all(gsub(string,"\\3",marc_field_cza_600$X600),"\\${2}.", "~"),NA)
}

marc_field_cza_600$`$$a` <- trim(marc_field_cza_600$`$$a`)
marc_field_cza_600$`$$d` <- trim(marc_field_cza_600$`$$d`)
marc_field_cza_600$`$$b` <- str_remove(trim(marc_field_cza_600$`$$b`),"\\.$")
marc_field_cza_600$field <- "X600"

cz_record_people_art_X600 <- marc_field_cza_600 %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_articles", field = "X600") %>%
  select(data_set, field,1:4)
cz_record_people_art_X600[] <- lapply(cz_record_people_art_X600, gsub, pattern=' NA', replacement='')
cz_record_people_art_X600[] <- lapply(cz_record_people_art_X600, gsub, pattern='\\|NA', replacement='')

#field X700
marc_field_cza_700 <- cz_articles %>%
  select(id,X700)%>%
  filter(X700!="") %>%
  cSplit(.,"X700",sep = "|",direction = "long") %>%
  filter(X700!="")
marc_field_cza_700 <- mutate(marc_field_cza_700,
               indicator = str_replace_all(marc_field_cza_700$X700,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X700,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_cza_700)[1]))
colnames(empty_table) <-subfield_list
marc_field_cza_700<-cbind(marc_field_cza_700,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field_cza_700$X700 <- str_replace(marc_field_cza_700$X700,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_cza_700[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_cza_700$X700),str_replace_all(gsub(string,"\\3",marc_field_cza_700$X700),"\\${2}.", "~"),NA)
}

marc_field_cza_700$`$$a` <- trim(marc_field_cza_700$`$$a`)
marc_field_cza_700$`$$d` <- trim(marc_field_cza_700$`$$d`)
marc_field_cza_700$field <- "X700"

cz_record_people_art_X700 <- marc_field_cza_700 %>%
  select(record_id = id, `$$a`,`$$d`) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  mutate(data_set = "cz_articles", field = "X700") %>%
  select(data_set, field,1:4)
cz_record_people_art_X700[] <- lapply(cz_record_people_art_X700, gsub, pattern=' NA', replacement='')
cz_record_people_art_X700[] <- lapply(cz_record_people_art_X700, gsub, pattern='\\|NA', replacement='')

#concatenate all cz art
cz_record_people_art <- rbind(cz_record_people_art_X100,cz_record_people_art_X600,cz_record_people_art_X700)
cz_record_people_art <- cz_record_people_art %>%
  mutate(id_osoby = paste("cza",seq.int(nrow(cz_record_people_art)),sep = ""))
names_of_columns <- colnames(cz_record_people_art)

cz_record_people_art <- cz_record_people_art %>%
  select(names_of_columns,id_osoby) %>%
  arrange(field,as.integer(record_id))
cz_record_people_art <- cz_record_people_art %>%
  mutate(name_form = paste(`$$a`, `$$d`, sep = " ")) %>% 
  select(data_set,field,record_id,name_form,name,id_osoby)
cz_record_people_art <- cz_record_people_art %>%
  mutate(subfield = "$$a")
cz_record_people_art[] <- lapply(cz_record_people_art, gsub, pattern=' NA', replacement='')
cz_record_people_art$name_form <- trim(cz_record_people_art$name_form)
cz_record_people_art <- cz_record_people_art %>%
  select(data_set,record_id,field,subfield,id_osoby,name_form) %>%
  mutate(name_form_id = paste(data_set,record_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", ""))

#pbl books

pbl_record_people_books_creators <- pbl_books %>%
  select(rekord_id,tworca_id,tworca_nazwisko,tworca_imie) %>%
  filter(!is.na(tworca_id))

pbl_record_people_books_creators <- pbl_record_people_books_creators %>%
  mutate(data_set = "pbl_books") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(tworca_nazwisko,tworca_imie,sep = "|")) %>%
  mutate(name_form = paste(tworca_nazwisko,tworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblt",tworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_books_authors <- pbl_books %>%
  select(rekord_id,autor_id,autor_nazwisko,autor_imie) %>%
  filter(!is.na(autor_id))

pbl_record_people_books_authors <- pbl_record_people_books_authors %>%
  mutate(data_set = "pbl_books") %>%
  mutate(field = "autorzy") %>%
  mutate(name = paste(autor_nazwisko,autor_imie,sep = "|")) %>%
  mutate(name_form = paste(autor_nazwisko,autor_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pbla",autor_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_books_coworkers <- pbl_books %>%
  select(rekord_id,wspoltworca_id,wspoltworca_nazwisko,wspoltworca_imie) %>%
  filter(!is.na(wspoltworca_id))

pbl_record_people_books_coworkers <- pbl_record_people_books_coworkers %>%
  mutate(data_set = "pbl_books") %>%
  mutate(field = "wspoltworcy") %>%
  mutate(name = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = "|")) %>%
  mutate(name_form = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblw",wspoltworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_books <- rbind(pbl_record_people_books_creators,pbl_record_people_books_authors,pbl_record_people_books_coworkers)


#pbl_articles

pbl_record_people_art_creators <- pbl_articles %>%
  select(rekord_id,tworca_id,tworca_nazwisko,tworca_imie) %>%
  filter(!is.na(tworca_id))

pbl_record_people_art_creators <- pbl_record_people_art_creators %>%
  mutate(data_set = "pbl_articles") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(tworca_nazwisko,tworca_imie,sep = "|")) %>%
  mutate(name_form = paste(tworca_nazwisko,tworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblt",tworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_art_authors <- pbl_articles %>%
  select(rekord_id,autor_id,autor_nazwisko,autor_imie) %>%
  filter(!is.na(autor_id))

pbl_record_people_art_authors <- pbl_record_people_art_authors %>%
  mutate(data_set = "pbl_articles") %>%
  mutate(field = "autorzy") %>%
  mutate(name = paste(autor_nazwisko,autor_imie,sep = "|")) %>%
  mutate(name_form = paste(autor_nazwisko,autor_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pbla",autor_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_art_coworkers <- pbl_articles %>%
  select(rekord_id,wspoltworca_id,wspoltworca_nazwisko,wspoltworca_imie) %>%
  filter(!is.na(wspoltworca_id))

pbl_record_people_art_coworkers <- pbl_record_people_art_coworkers %>%
  mutate(data_set = "pbl_articles") %>%
  mutate(field = "wspoltworcy") %>%
  mutate(name = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = "|")) %>%
  mutate(name_form = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblw",wspoltworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_art <- rbind(pbl_record_people_art_creators,pbl_record_people_art_authors,pbl_record_people_art_coworkers)

```

```{r merge personal data}
#putting all together
record_people <- rbind(bn_record_people,cz_record_people,cz_record_people_art,pbl_record_people_books,pbl_record_people_art)

#test <- record_people %>%
#  filter(grepl("Amsterdamski|erski",name_form))

#id tymczas, nazwa, id nazwy, id osoby
tab_2 <- record_people %>%
  select(name_form,name_form_id,name_simple,id_osoby) %>%
  group_by(name_simple) %>%
  mutate(name_form_id = paste(unique(name_form_id),collapse = "|")) %>%
  mutate(name_form = paste(unique(name_form), collapse = "|")) %>%
  mutate(id_osoby = paste(unique(id_osoby), collapse = "|")) %>%
  ungroup() %>%
  unique()
tab_2$temp_id <- seq.int(nrow(tab_2))
tab_2 <- tab_2 %>%
  select(temp_id,name_form, name_simple, name_form_id, id_osoby)
# czenie po id osoby

tab_3 <- tab_2 %>%
  mutate(name_simple_short = str_extract(name_simple,"(^[a-zaeiiouycdgklnrsstz]+)")) %>%
  group_by(name_simple_short) %>%
  mutate(temp_id = paste(unique(temp_id),collapse = "|")) %>%
  mutate(name_form_id = paste(unique(name_form_id),collapse = "|")) %>%
  mutate(name_form = paste(unique(name_form), collapse = "|")) %>%
  mutate(id_osoby = paste(unique(id_osoby), collapse = "|")) %>%
  mutate(name_simple = paste(unique(name_simple), collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  select(-name_simple_short)

id_osoby <- tab_3 %>%
  select(id_osoby,temp_id2 = temp_id)

id_osoby <- cSplit(id_osoby,"id_osoby",sep = "|",direction = "long") %>%
  group_by(id_osoby) %>%
  mutate(temp_id2 = paste(temp_id2,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(id_osoby = paste(id_osoby,"|",sep = ""))
tab_3$id_osoby <- paste(tab_3$id_osoby,"|",sep = "")

tab_4 <- sqldf::sqldf("select *
                     from tab_3 a
                     join id_osoby b on a.id_osoby like ('%'||b.id_osoby||'%')") %>%
  select(-temp_id,-id_osoby..6) %>%
  unique() %>%
  mutate(temp_id2 = str_extract(temp_id2,"(^\\d+)(?=\\||$)")) %>%
  group_by(temp_id2) %>%
  mutate(name_form = paste(unique(name_form),collapse = "|")) %>%
  mutate(name_simple = paste(unique(name_simple),collapse = "|")) %>%
  mutate(name_form_id = paste(unique(name_form_id),collapse = "|")) %>%
  mutate(id_osoby = paste(unique(id_osoby),collapse = "")) %>%
  ungroup() %>%
  unique()

x <- 1:length(tab_4$temp_id2)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  tab_4$id_osoby[i] <- paste(paste(unique(unlist(strsplit(tab_4$id_osoby[i],"\\|"))),collapse = "|"),"|",sep = "")
}

tab_4 <- tab_4 %>%
  select(id = temp_id2,name_form,name_simple,name_form_id,id_osoby)

write.csv2(tab_4, "C:/Users/Cezary/Desktop/samizdat_kartoteka_osb.csv", row.names = F, na = '', fileEncoding = 'UTF-8')
```

```{r preparing file for institutions}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X110
marc_field <- bn_books %>%
  select(id,X110)%>%
  filter(X110!="") %>%
  cSplit(.,"X110",sep = "|",direction = "long") %>%
  filter(X110!="")
subfield_list<- str_extract_all(bn_books$X110,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X110 <- str_replace(marc_field$X110,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X110),str_replace_all(gsub(string,"\\3",marc_field$X110),"\\%.", "~"),NA)
}
bn_institutions_110 <- marc_field %>%
  mutate(MRC = "110",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = `%2`,
         Related_Entity_Main_Entity = NA,
         Located_Location = `%6`,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
sub_institutions <- marc_field %>%
  filter(!is.na(`%2`)) %>%
  mutate(MRC = "110",
         Entity_Name = `%2`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = `%1`,
         Located_Location = `%7`,
         subfield = "%2") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
bn_institutions_110 <- rbind(bn_institutions_110,sub_institutions)

#field X120
marc_field <- bn_books %>%
  select(id,X120)%>%
  filter(X120!="") %>%
  cSplit(.,"X120",sep = "|",direction = "long") %>%
  filter(X120!="")
subfield_list<- str_extract_all(bn_books$X120,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X120 <- str_replace(marc_field$X120,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X120),str_replace_all(gsub(string,"\\3",marc_field$X120),"\\%.", "~"),NA)
}

bn_institutions_120 <- marc_field %>%
  mutate(MRC = "120",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = `%2`,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
sub_institutions <- marc_field %>%
  filter(!is.na(`%2`)) %>%
  mutate(MRC = "120",
         Entity_Name = `%2`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = `%1`,
         Located_Location = NA,
         subfield = "%2") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
bn_institutions_120 <- rbind(bn_institutions_120,sub_institutions)

#field X210
marc_field <- bn_books %>%
  select(id,X210)%>%
  filter(X210!="") %>%
  cSplit(.,"X210",sep = "|",direction = "long") %>%
  filter(X210!="")
subfield_list<- str_extract_all(bn_books$X210,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X210 <- str_replace(marc_field$X210,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X210),str_replace_all(gsub(string,"\\3",marc_field$X210),"\\%.", "~"),NA)
}

bn_institutions_210 <- marc_field %>%
  mutate(MRC = "210",
         Entity_Name = `%c`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = `%a`,
         subfield = "%c") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
sub_institutions <- marc_field %>%
  filter(!is.na(`%g`)) %>%
  mutate(MRC = "210",
         Entity_Name = `%g`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = `%e`,
         subfield = "%g") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
bn_institutions_210 <- rbind(bn_institutions_210,sub_institutions)
#field X225
marc_field <- bn_books %>%
  select(id,X225)%>%
  filter(X225!="") %>%
  cSplit(.,"X225",sep = "|",direction = "long") %>%
  filter(X225!="")
subfield_list<- str_extract_all(bn_books$X225,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X225 <- str_replace(marc_field$X225,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X225),str_replace_all(gsub(string,"\\3",marc_field$X225),"\\%.", "~"),NA)
}
bn_institutions_225 <- marc_field %>%
  mutate(MRC = "225",
         Entity_Name = `%f`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%f") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)

#field X710
marc_field <- bn_books %>%
  select(id,X710)%>%
  filter(X710!="") %>%
  cSplit(.,"X710",sep = "|",direction = "long") %>%
  filter(X710!="")
subfield_list<- str_extract_all(bn_books$X710,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X710 <- str_replace(marc_field$X710,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X710),str_replace_all(gsub(string,"\\3",marc_field$X710),"\\%.", "~"),NA)
}
bn_institutions_710 <- marc_field %>%
  mutate(MRC = "710",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X711
marc_field <- bn_books %>%
  select(id,X711)%>%
  filter(X711!="") %>%
  cSplit(.,"X711",sep = "|",direction = "long") %>%
  filter(X711!="")
subfield_list<- str_extract_all(bn_books$X711,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X711 <- str_replace(marc_field$X711,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X711),str_replace_all(gsub(string,"\\3",marc_field$X711),"\\%.", "~"),NA)
}
bn_institutions_711 <- marc_field %>%
  mutate(MRC = "711",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#connecting bn institutions
bn_books_institutions <- rbind(bn_institutions_110,bn_institutions_120,bn_institutions_210,bn_institutions_225,bn_institutions_710,bn_institutions_711) %>%
  mutate(source = "bn_books")

#cz_books 110, 264, 610, 710, 787(?)
#field X110
marc_field <- cz_books %>%
  select(id,X110)%>%
  filter(X110!="") %>%
  cSplit(.,"X110",sep = "|",direction = "long") %>%
  filter(X110!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X110,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X110,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X110 <- str_replace(marc_field$X110,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X110),str_replace_all(gsub(string,"\\3",marc_field$X110),"\\${2}.", "~"),NA)
}
cz_institutions_110 <- marc_field %>%
  mutate(MRC = "110",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)

#field X264
marc_field <- cz_books %>%
  select(id,X264)%>%
  filter(X264!="") %>%
  cSplit(.,"X264",sep = "|",direction = "long") %>%
  filter(X264!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X264,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X264,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X264 <- str_replace(marc_field$X264,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X264),str_replace_all(gsub(string,"\\3",marc_field$X264),"\\${2}.", "~"),NA)
}
cz_institutions_264 <- marc_field %>%
  mutate(MRC = "264",
         Entity_Name = `$$b`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = `$$a`,
         subfield = "$$b") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)

#field X610
marc_field <- cz_books %>%
  select(id,X610)%>%
  filter(X610!="") %>%
  cSplit(.,"X610",sep = "|",direction = "long") %>%
  filter(X610!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X610,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X610,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X610 <- str_replace(marc_field$X610,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X610),str_replace_all(gsub(string,"\\3",marc_field$X610),"\\${2}.", "~"),NA)
}
cz_institutions_610 <- marc_field %>%
  mutate(MRC = "610",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X710
marc_field <- cz_books %>%
  select(id,X710)%>%
  filter(X710!="") %>%
  cSplit(.,"X710",sep = "|",direction = "long") %>%
  filter(X710!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X710,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X710,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X710 <- str_replace(marc_field$X710,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X710),str_replace_all(gsub(string,"\\3",marc_field$X710),"\\${2}.", "~"),NA)
}
cz_institutions_710 <- marc_field %>%
  mutate(MRC = "710",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#connecting cz books institutions
cz_books_institutions <- rbind(cz_institutions_110,cz_institutions_264,cz_institutions_610,cz_institutions_710) %>%
  mutate(source = "cz_books")
#cz_articles 110, 610, 710

#field X110
marc_field <- cz_articles %>%
  select(id,X110)%>%
  filter(X110!="") %>%
  cSplit(.,"X110",sep = "|",direction = "long") %>%
  filter(X110!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X110,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X110,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X110 <- str_replace(marc_field$X110,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X110),str_replace_all(gsub(string,"\\3",marc_field$X110),"\\${2}.", "~"),NA)
}
cz_institutions_110 <- marc_field %>%
  mutate(MRC = "110",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X610
marc_field <- cz_articles %>%
  select(id,X610)%>%
  filter(X610!="") %>%
  cSplit(.,"X610",sep = "|",direction = "long") %>%
  filter(X610!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X610,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X610,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X610 <- str_replace(marc_field$X610,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X610),str_replace_all(gsub(string,"\\3",marc_field$X610),"\\${2}.", "~"),NA)
}
cz_institutions_610 <- marc_field %>%
  mutate(MRC = "610",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X710
marc_field <- cz_articles %>%
  select(id,X710)%>%
  filter(X710!="") %>%
  cSplit(.,"X710",sep = "|",direction = "long") %>%
  filter(X710!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X710,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X710,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X710 <- str_replace(marc_field$X710,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X710),str_replace_all(gsub(string,"\\3",marc_field$X710),"\\${2}.", "~"),NA)
}
cz_institutions_710 <- marc_field %>%
  mutate(MRC = "710",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#connecting cz articles institutions
cz_articles_institutions <- rbind(cz_institutions_110,cz_institutions_610,cz_institutions_710) %>%
  mutate(source = "cz_articles")

#pbl_books
#publishing house
pbl_books_publishing_house <- pbl_books %>%
  select(rekord_id,wydawnictwo,miejscowosc) %>%
  unique() %>%
  mutate(MRC = NA,
         Entity_Name = wydawnictwo,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = miejscowosc,
         subfield = "publishing_house",
         id = rekord_id) %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#subject headings
pbl_books_sh <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>%
  filter(HP_NAZWA %in% c("Biblioteki","Filmowe instytucje, kluby, przedsibiorstwa","Fundacje, fundusze kulturalne, stypendia","Grupy literackie i artystyczne","Instytucje kulturalne, pastwowe, spoeczne obce","Instytucje kulturalne, pastwowe, spoeczne polskie","Instytuty pozauczelniane, komitety i towarzystwa naukowe w Polsce","Instytuty pozauczelniane, komitety i towarzystwa naukowe za granic","Muzea obce","Muzea polskie","Teatry obce","Teatry polskie historia","Teatry polskie wspczesne","Uczelniane instytuty (wydziay, zakady, orodki badawcze) obce","Uczelniane instytuty (wydziay, zakady, orodki badawcze) polskie","Uniwersytety, szkoy wysze i inne uczelnie obce","Uniwersytety, szkoy wysze i inne uczelnie polskie","Wydawnictwa polskie do 1945 roku","Wydawnictwa polskie po 1945 roku","Zwizki, kluby, koa, stowarzyszenia twrcze obce","Zwizki, kluby, koa, stowarzyszenia twrcze polskie")) %>%
  mutate(MRC = NA,
         Entity_Name = KH_NAZWA,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "subject_heading",
         id = rekord_id) %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
pbl_books_institutions <- rbind(pbl_books_publishing_house,pbl_books_sh) %>%
  mutate(source = "pbl_books")
#pbl_articles
#subject headings
pbl_articles_institutions <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>%
  filter(HP_NAZWA %in% c("Biblioteki","Filmowe instytucje, kluby, przedsibiorstwa","Fundacje, fundusze kulturalne, stypendia","Grupy literackie i artystyczne","Instytucje kulturalne, pastwowe, spoeczne obce","Instytucje kulturalne, pastwowe, spoeczne polskie","Instytuty pozauczelniane, komitety i towarzystwa naukowe w Polsce","Instytuty pozauczelniane, komitety i towarzystwa naukowe za granic","Muzea obce","Muzea polskie","Teatry obce","Teatry polskie historia","Teatry polskie wspczesne","Uczelniane instytuty (wydziay, zakady, orodki badawcze) obce","Uczelniane instytuty (wydziay, zakady, orodki badawcze) polskie","Uniwersytety, szkoy wysze i inne uczelnie obce","Uniwersytety, szkoy wysze i inne uczelnie polskie","Wydawnictwa polskie do 1945 roku","Wydawnictwa polskie po 1945 roku","Zwizki, kluby, koa, stowarzyszenia twrcze obce","Zwizki, kluby, koa, stowarzyszenia twrcze polskie")) %>%
  mutate(MRC = NA,
         Entity_Name = KH_NAZWA,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "subject_heading",
         id = rekord_id) %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield) %>%
  mutate(source = "pbl_articles")
#merge all institutions
institutions <- rbind(bn_books_institutions,cz_books_institutions,cz_articles_institutions,pbl_books_institutions,pbl_articles_institutions) %>%
  mutate(Located_Location = str_remove(str_remove(trim(Located_Location),"^\\["),"\\]$")) %>%
  group_by(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location) %>%
  mutate(group = paste(paste(source,MRC,subfield,id,sep = ""),collapse = "|")) %>%
  ungroup() %>%
  select(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,group) %>%
  unique() %>%
  arrange(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity)


write.csv2(institutions, "C:/Users/Cezary/Desktop/samizdat_kartoteka_instytucji.csv", row.names = F, na = '', fileEncoding = 'UTF-8')
```

```{r preparing file for events}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X120
marc_field <- bn_books %>%
  select(id,X120)%>%
  filter(X120!="") %>%
  cSplit(.,"X120",sep = "|",direction = "long") %>%
  filter(X120!="")
subfield_list<- str_extract_all(bn_books$X120,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X120 <- str_replace(marc_field$X120,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X120),str_replace_all(gsub(string,"\\3",marc_field$X120),"\\%.", "~"),NA)
}

bn_events <- marc_field %>%
  mutate(MRC = "120",
         Event_Name = `%3`,
         Event_Other_Names = `%r`,
         Event_Number = `%4`,
         Event_Number_Arabic = `%n`,
         Event_Year = `%5`,
         Located = `%8`,
         Organiser_Main = `%1`,
         Organiser_Sub = `%2`,
         subfield = "%3") %>%
  select(id,MRC,Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,subfield) %>%
  mutate(source = "bn_books")

#cz_books
#field X611
marc_field <- cz_books %>%
  select(id,X611)%>%
  filter(X611!="") %>%
  cSplit(.,"X611",sep = "|",direction = "long") %>%
  filter(X611!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X611,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X611,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X611 <- str_replace(marc_field$X611,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X611),str_replace_all(gsub(string,"\\3",marc_field$X611),"\\${2}.", "~"),NA)
}
cz_books_events <- marc_field %>%
  mutate(MRC = "611",
         Event_Name = `$$a`,
         Event_Other_Names = NA,
         Event_Number = NA,
         Event_Number_Arabic = NA,
         Event_Year = `$$d`,
         Located = `$$c`,
         Organiser_Main = NA,
         Organiser_Sub = NA,
         subfield = "$$a") %>%
  select(id,MRC,Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,subfield) %>%
  mutate(source = "cz_books")
#cz_articles
#field X611
marc_field <- cz_articles %>%
  select(id,X611)%>%
  filter(X611!="") %>%
  cSplit(.,"X611",sep = "|",direction = "long") %>%
  filter(X611!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X611,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X611,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X611 <- str_replace(marc_field$X611,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X611),str_replace_all(gsub(string,"\\3",marc_field$X611),"\\${2}.", "~"),NA)
}
cz_articles_events <- marc_field %>%
  mutate(MRC = "611",
         Event_Name = `$$a`,
         Event_Other_Names = NA,
         Event_Number = NA,
         Event_Number_Arabic = `$$n`,
         Event_Year = `$$d`,
         Located = `$$c`,
         Organiser_Main = NA,
         Organiser_Sub = NA,
         subfield = "$$a") %>%
  select(id,MRC,Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,subfield) %>%
  mutate(source = "cz_articles")
cz_events <- rbind(cz_books_events,cz_articles_events)

#merge all events
events <- rbind(bn_events,cz_books_events,cz_articles_events) %>%
  group_by(Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub) %>%
  mutate(group = paste(paste(source,MRC,subfield,id,sep = ""),collapse = "|")) %>%
  ungroup() %>%
  select(Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,group) %>%
  unique() %>%
  arrange(Event_Name,Event_Year)

write.csv2(events, "C:/Users/Cezary/Desktop/samizdat_kartoteka_wydarze.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

```

```{r preparing file for series}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X225
marc_field <- bn_books %>%
  select(id,X225)%>%
  filter(X225!="") %>%
  cSplit(.,"X225",sep = "|",direction = "long") %>%
  filter(X225!="")
subfield_list<- str_extract_all(bn_books$X225,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X225 <- str_replace(marc_field$X225,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X225),str_replace_all(gsub(string,"\\3",marc_field$X225),"\\%.", "~"),NA)
}

bn_series_225 <- marc_field %>%
  mutate(MRC = "225",
         Series_Title = `%a`,
         Addition_to_Title = `%e`,
         Creator = `%f`,
         Sub_Series = `%c`,
         Main_Series = NA,
         subfield = "%a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
bn_more_series <- marc_field %>%
  filter(!is.na(`%c`)) %>%
  mutate(MRC = "225",
         Series_Title = `%c`,
         Addition_to_Title = NA,
         Creator = `%f`,
         Sub_Series = NA,
         Main_Series = `%a`,
         subfield = "%c") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
#field X226
marc_field <- bn_books %>%
  select(id,X226)%>%
  filter(X226!="") %>%
  cSplit(.,"X226",sep = "|",direction = "long") %>%
  filter(X226!="")
subfield_list<- str_extract_all(bn_books$X226,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X226 <- str_replace(marc_field$X226,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X226),str_replace_all(gsub(string,"\\3",marc_field$X226),"\\%.", "~"),NA)
}
bn_series_226 <- marc_field %>%
  mutate(MRC = "226",
         Series_Title = `%a`,
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "%a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)


bn_series <- rbind(bn_series_225,bn_more_series,bn_series_226) %>%
  mutate(source = "bn_books")

#cz_books
#field X490
marc_field <- cz_books %>%
  select(id,X490)%>%
  filter(X490!="") %>%
  cSplit(.,"X490",sep = "|",direction = "long") %>%
  filter(X490!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X490,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X490,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X490 <- str_replace(marc_field$X490,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X490),str_replace_all(gsub(string,"\\3",marc_field$X490),"\\${2}.", "~"),NA)
}
cz_series_490 <- marc_field %>%
  mutate(MRC = "490",
         Series_Title = str_remove(`$$a`," ;$"),
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "$$a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
#field X830
marc_field <- cz_books %>%
  select(id,X830)%>%
  filter(X830!="") %>%
  cSplit(.,"X830",sep = "|",direction = "long") %>%
  filter(X830!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X830,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X830,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X830 <- str_replace(marc_field$X830,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X830),str_replace_all(gsub(string,"\\3",marc_field$X830),"\\${2}.", "~"),NA)
}
cz_series_830 <- marc_field %>%
  mutate(MRC = "830",
         Series_Title = str_remove(`$$a`," ;$"),
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "$$a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
cz_series <- rbind(cz_series_490,cz_series_830) %>%
  mutate(source = "cz_books")
#pbl_books
pbl_series <- pbl_books %>%
  select(rekord_id,ZA_SERIA_WYDAWNICZA) %>%
  unique() %>%
  mutate(MRC = NA,
         Series_Title = str_remove(str_remove(ZA_SERIA_WYDAWNICZA,"^\\("),"\\)$"),
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "za_seria_wydawnicza",
         id = rekord_id) %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield) %>%
  mutate(source = "pbl_books")

#merge all series
series <- rbind(bn_series,cz_series,pbl_series) %>%
  group_by(Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series) %>%
  mutate(group = paste(paste(source,MRC,subfield,id,sep = ""),collapse = "|")) %>%
  ungroup() %>%
  select(Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,group) %>%
  unique() %>%
  arrange(Series_Title,Addition_to_Title)

write.csv2(series, "C:/Users/Cezary/Desktop/samizdat_kartoteka_serii.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

```

```{r kartoteki po pracach dziewczyn}
#osoby
record_people <- rbind(bn_record_people,cz_record_people,cz_record_people_art,pbl_record_people_books,pbl_record_people_art) %>% 
   mutate(record_id = as.integer(record_id)) %>%
  left_join(bind_rows(marc_field_bnb_100,marc_field_bnb_700,marc_field_bnb_701) %>% select(-X100,-X700,-X701),c("record_id"="id","field")) %>% 
  left_join(bind_rows(marc_field_czb_100,marc_field_czb_600,marc_field_czb_700,marc_field_cza_100,marc_field_cza_600,marc_field_cza_700) %>% select(-X100,-X600,-X700),c("record_id"="id","field")) %>% 
  unite("total",`%1`:`$$q`,sep = " ", remove = FALSE, na.rm = TRUE)

x <- 1:nrow(record_people)
for (i in x) {
  progress(match(i,x), max.value = length(x))
  record_people$person_match[i] <- ifelse(grepl(record_people$name_form[i],record_people$total[i]),TRUE,FALSE)
}

kartoteka_osob <- sheets_read(ss = "1Y8Y_pfkuKiv5npL6QJAXWbDO6twIJqsK3ArvaokjFkU", sheet = "samizdat",col_types = "c") %>% 
  select(-test) %>% 
  mutate(name_form = str_remove(name_form,", NA")) %>% 
  cSplit(c("name_form","name_form_id","id_osoby"),sep = "|",direction = "long") %>% 
  filter(!is.na(name_form_id)) %>% 
  group_by(temp_id) %>% 
  fill(name_form) %>% 
  ungroup() %>% 
  cSplit("name_form_id",sep = "-",direction = "wide") %>% 
  mutate(name_form_id_4 = ifelse(grepl("pbla",name_form_id_3),"autorzy",
                                 ifelse(grepl("pblw",name_form_id_3),"wspoltworcy",as.character(name_form_id_4)))) %>% 
  unite("name_form_id",name_form_id_1:name_form_id_5,sep = "-")

nodegoat_people <- record_people %>% 
  filter(person_match==TRUE) %>% 
  unique() %>% 
  left_join(kartoteka_osob %>% select(name_form_id,group_id),by="name_form_id") %>% 
  filter(!is.na(group_id)) %>% 
  mutate(name_form = str_remove(name_form,"(, NA)+"),
         Project_ID = NA,
         LOD_ID = NA,
         Index_Name = ifelse(data_set=="bn_books",paste3(`%1`,`%2`,`%3`,`%4`,`%5`,`%6`,sep = " "),
                             ifelse(data_set %in% c("cz_books","cz_articles"),paste3(`$$a`),as.character(name_form))),
         Name = ifelse(data_set=="bn_books",paste3(`%1`,`%4`),
                             ifelse(data_set %in% c("cz_books","cz_articles"),str_replace(`$$a`,"(.*?)(,.*$)","\\1"),as.character(str_replace(name_form,"(.*?)(,.*$)","\\1")))),
         Given_Name = ifelse(data_set=="bn_books",paste3(`%2`),
                             ifelse(data_set %in% c("cz_books","cz_articles")&grepl(",",Index_Name),str_replace(`$$a`,"(.*?, )(.*$)","\\2"),
                                    ifelse(data_set %in% c("cz_books","cz_articles"),NA,as.character(str_replace(name_form,"(.*?, )(.*$)","\\2"))))),
         Pseudonym_Kryptonym = ifelse(data_set=="bn_books",str_remove(paste3(trim(`%p`),trim(`%k`),sep = "; "),"; $"),NA),
         True_Name = `%w`,
         Other_Name_Form = str_remove(paste3(`%o`,`%s`,`%r`,`%m`,sep = "; "),"^; |; $"),
         Addition_to_Name = ifelse(data_set=="bn_books",paste3(`%5`),
                             ifelse(data_set %in% c("cz_books","cz_articles"),paste3(`$$c`),NA)),
         Numeration = ifelse(data_set=="bn_books",paste3(`%3`),
                             ifelse(data_set %in% c("cz_books","cz_articles"),paste3(`$$b`),NA)),
         Numeration_arabic = ifelse(data_set=="bn_books",paste3(`%n`),NA),
         Birth = ifelse(data_set=="bn_books",str_extract(`%d`,"\\d+(?=\\-)"),
                             ifelse(data_set %in% c("cz_books","cz_articles"),str_extract(`$$d`,"\\d+(?=\\-)"),NA)),
         Death = ifelse(data_set=="bn_books",str_extract(`%d`,"(?<=\\-)\\d+"),
                             ifelse(data_set %in% c("cz_books","cz_articles"),str_extract(`$$d`,"(?=\\-)\\d+"),NA))) %>% 
  select(id_osoby,group_id,Project_ID,LOD_ID,Index_Name,Name,Given_Name,Pseudonym_Kryptonym,True_Name,Other_Name_Form,Addition_to_Name,Numeration,Numeration_arabic,Birth,Death,name_form_id) %>% 
  group_by(group_id) %>% 
  mutate(id_osoby = paste(unique(na.omit(id_osoby)),collapse = "|"),
         Project_ID = paste(unique(na.omit(Project_ID)),collapse = "|"),
         Index_Name = paste(unique(na.omit(Index_Name)),collapse = "|"),
         Name = paste(unique(na.omit(Name)),collapse = "|"),
         Given_Name = paste(unique(na.omit(Given_Name)),collapse = "|"),
         Pseudonym_Kryptonym = paste(unique(na.omit(Pseudonym_Kryptonym)),collapse = "; "),
         True_Name = paste(unique(na.omit(True_Name)),collapse = "|"),
         Other_Name_Form = paste(unique(na.omit(Other_Name_Form)),collapse = "; "),
         Addition_to_Name = paste(unique(na.omit(Addition_to_Name)),collapse = "|"),
         Numeration = paste(unique(na.omit(Numeration)),collapse = "|"),
         Birth = paste(unique(na.omit(Birth)),collapse = "|"),
         Death = paste(unique(na.omit(Death)),collapse = "|"),
         name_form_id = paste(unique(na.omit(name_form_id)),collapse = "|")) %>% 
  ungroup() %>% 
  group_by(id_osoby) %>% 
  mutate(group_id = paste(unique(na.omit(group_id)),collapse = "|"),
         Project_ID = paste(unique(na.omit(Project_ID)),collapse = "|"),
         Index_Name = paste(unique(na.omit(Index_Name)),collapse = "|"),
         Name = paste(unique(na.omit(Name)),collapse = "|"),
         Given_Name = paste(unique(na.omit(Given_Name)),collapse = "|"),
         Pseudonym_Kryptonym = paste(unique(na.omit(Pseudonym_Kryptonym)),collapse = "; "),
         True_Name = paste(unique(na.omit(True_Name)),collapse = "|"),
         Other_Name_Form = paste(unique(na.omit(Other_Name_Form)),collapse = "; "),
         Addition_to_Name = paste(unique(na.omit(Addition_to_Name)),collapse = "|"),
         Numeration = paste(unique(na.omit(Numeration)),collapse = "|"),
         Birth = paste(unique(na.omit(Birth)),collapse = "|"),
         Death = paste(unique(na.omit(Death)),collapse = "|"),
         name_form_id = paste(unique(na.omit(name_form_id)),collapse = "|")) %>% 
  ungroup() %>% 
  arrange(id_osoby,group_id) %>% 
  unique() %>% 
  mutate(Other_Name_Form = ifelse(grepl("\\|",Index_Name),paste3(Other_Name_Form,str_extract(Index_Name,"(?<=\\|)(.*)"),sep = "; "),paste3(Other_Name_Form)),
         Name = ifelse(grepl("\\|",Name),str_extract(Name,"(.*?)(?=\\|)"),paste3(Name)),
         Given_Name = ifelse(grepl("\\|",Given_Name),str_extract(Given_Name,"(.*?)(?=\\|)"),paste3(Given_Name)),
         Birth = ifelse(grepl("\\|",Birth),str_extract(Birth,"(.*?)(?=\\|)"),paste3(Birth)),
         Index_Name = ifelse(grepl("\\|",Index_Name),str_extract(Index_Name,"(.*?)(?=\\|)"),paste3(Index_Name))) %>% 
  group_by_at(vars(c(Index_Name,Birth,Death))) %>% 
  mutate(group_id = paste(unique(na.omit(group_id)),collapse = "|"),
         Project_ID = paste(unique(na.omit(Project_ID)),collapse = "|"),
         id_osoby = paste(unique(na.omit(id_osoby)),collapse = "|"),
         Name = paste(unique(na.omit(Name)),collapse = "|"),
         Given_Name = paste(unique(na.omit(Given_Name)),collapse = "|"),
         Pseudonym_Kryptonym = paste(unique(na.omit(Pseudonym_Kryptonym)),collapse = "; "),
         True_Name = paste(unique(na.omit(True_Name)),collapse = "|"),
         Other_Name_Form = paste(unique(na.omit(Other_Name_Form)),collapse = "; "),
         Addition_to_Name = paste(unique(na.omit(Addition_to_Name)),collapse = "|"),
         Numeration = paste(unique(na.omit(Numeration)),collapse = "|"),
         name_form_id = paste(unique(na.omit(name_form_id)),collapse = "|")) %>% 
  ungroup() %>% 
  arrange(id_osoby,group_id) %>% 
  unique() %>% 
  mutate(Project_ID = 1:n())


write.xlsx(nodegoat_people, "C:/Users/Cezary/Desktop/nodegoat_people.xlsx")
write.csv2(nodegoat_people, file = "C:/Users/Cezary/Desktop/nodegoat_people.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

#instytucje

kartoteka_instytucji <- sheets_read(ss = "1MX8oqQly65GzkEhwKGf7NqBc4L4B5mNj12NtgLgB5Bs", sheet = "Arkusz1",col_types = "c")

nodegoat_institutions <- kartoteka_instytucji %>% 
  mutate(Entity_Name = ifelse(str_count(Entity_Name,"\\[")>str_count(Entity_Name,"\\]"),str_remove_all(Entity_Name,"^\\["),
                               ifelse(str_count(Entity_Name,"\\[")<str_count(Entity_Name,"\\]"),str_remove_all(Entity_Name,"\\]$"),paste3(Entity_Name)))) %>% 
  group_by(group_id) %>% 
  mutate(Entity_Name = paste(unique(na.omit(Entity_Name)),collapse = "|"),
         Related_Entity_Sub_Entity = paste(unique(na.omit(Related_Entity_Sub_Entity)),collapse = "|"),
         Related_Entity_Main_Entity = paste(unique(na.omit(Related_Entity_Main_Entity)),collapse = "|"),
         Located_Location = paste(unique(na.omit(Located_Location)),collapse = "|"),
         group = paste(unique(na.omit(group)),collapse = "|")) %>% 
  ungroup() %>% 
  unique() %>% 
  group_by_at(vars(c(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location))) %>% 
  mutate(group_id = paste(unique(na.omit(group_id)),collapse = "|"),
         group = paste(unique(na.omit(group)),collapse = "|")) %>% 
  ungroup() %>% 
  unique() %>% 
  arrange(Entity_Name,-nchar(Located_Location)) %>% 
  mutate(Project_ID = 1:n(),
         LOD_ID = NA)
nodegoat_institutions <- nodegoat_institutions %>% 
  left_join(nodegoat_institutions %>% select(Project_ID_sub=Project_ID,Entity_Name,Related_Entity_Main_Entity),by = c("Related_Entity_Sub_Entity"="Entity_Name","Entity_Name"="Related_Entity_Main_Entity"))
nodegoat_institutions <- nodegoat_institutions %>% 
  left_join(nodegoat_institutions %>% select(Project_ID_main=Project_ID,Entity_Name,Related_Entity_Sub_Entity),by = c("Related_Entity_Main_Entity"="Entity_Name","Entity_Name"="Related_Entity_Sub_Entity")) %>% 
  mutate(Related_Entity_Sub_Entity = ifelse(Related_Entity_Sub_Entity!="",as.integer(Project_ID_sub),""),
         Related_Entity_Main_Entity = ifelse(Related_Entity_Main_Entity!="",as.integer(Project_ID_main),"")) %>% 
  select(group_id:LOD_ID)

write.csv2(nodegoat_institutions, file = "C:/Users/Cezary/Desktop/nodegoat_institutions.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

#wydarzenia

kartoteka_wydarzen <- sheets_read(ss = "1BosLyDVa7uxNTxw3Lt19PPADx8ZZcEuLYDnl--6vVDM", sheet = "Arkusz1",col_types = "c")

kartoteka_wydarzen[is.na(kartoteka_wydarzen)]<-""

nodegoat_events <- kartoteka_wydarzen %>% 
  mutate(Event_Number_Arabic = str_extract(Event_Number_Arabic,"\\d+"),
         Event_Year = str_extract(Event_Year,"\\d+"),
         Located = str_remove_all(Located,"^\\(|\\)$")) %>% 
  left_join(nodegoat_institutions %>% select(Project_ID_institution=Project_ID,Entity_Name,Related_Entity_Sub_Entity) %>% cSplit(.,"Entity_Name",sep = "|",direction = "long"),by = c("Organiser_Main"="Entity_Name","Organiser_Sub"="Related_Entity_Sub_Entity"))

nodegoat_events[nodegoat_events==""]<-NA

nodegoat_events <- nodegoat_events%>% 
  arrange(as.integer(group_id),Event_Name)

nodegoat_events <- nodegoat_events[!duplicated(nodegoat_events$group_id),] %>% 
  left_join(nodegoat_institutions %>% select(Project_ID_institution2=Project_ID,Entity_Name,Related_Entity_Main_Entity),by = c("Organiser_Main"="Related_Entity_Main_Entity","Organiser_Sub"="Entity_Name")) %>% 
  mutate(Organiser_Main = ifelse(Organiser_Main=="","",paste3(Project_ID_institution)),
         Organiser_Sub = ifelse(Organiser_Sub=="","",paste3(Project_ID_institution2))) %>% 
  group_by(group_id) %>% 
  mutate(Event_Name = paste(unique(na.omit(Event_Name)),collapse = "|"),
         Event_Other_Names = paste(unique(na.omit(Event_Other_Names)),collapse = "|"),
         Event_Number = paste(unique(na.omit(Event_Number)),collapse = "|"),
         Event_Number_Arabic = paste(unique(na.omit(Event_Number_Arabic)),collapse = "|"),
         Event_Year = paste(unique(na.omit(Event_Year)),collapse = "|"),
         Located = paste(unique(na.omit(Located)),collapse = "|"),
         Organiser_Main = paste(unique(na.omit(Organiser_Main)),collapse = "|"),
         Organiser_Sub = paste(unique(na.omit(Organiser_Sub)),collapse = "|"),
         group = paste(unique(na.omit(group)),collapse = "|")) %>% 
  ungroup() %>% 
  unique() %>% 
  mutate(Project_ID = 1:n()) %>% 
  select(group_id:group,Project_ID)

write.csv2(nodegoat_events, file = "C:/Users/Cezary/Desktop/nodegoat_events.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

#serie

kartoteka_serii <- sheets_read(ss = "1UPBWh8743mJWVGFD1fg3CHx03eOH8lSWcX090QIFJgs", sheet = "Arkusz1",col_types = "c")

nodegoat_series <- kartoteka_serii %>% 
  mutate(Series_Title = ifelse(str_count(Series_Title,"\\[")>str_count(Series_Title,"\\]"),str_remove_all(Series_Title,"^\\["),
                               ifelse(str_count(Series_Title,"\\[")<str_count(Series_Title,"\\]"),str_remove_all(Series_Title,"\\]$"),paste3(Series_Title))),
         Creator = ifelse(str_count(Creator,"\\[")>str_count(Creator,"\\]"),str_remove_all(Creator,"^\\["),
                               ifelse(str_count(Creator,"\\[")<str_count(Creator,"\\]"),str_remove_all(Creator,"\\]$"),paste3(Creator)))) %>% 
  mutate(nr_zapisu = str_extract(group,"\\d+(?!.*\\d+)")) %>% 
  left_join(bn_books %>% select(id,X210) %>% mutate(id=as.character(id)),by = c("nr_zapisu"="id")) %>% 
  mutate(X210 = str_remove_all(str_extract(X210,"(?<=%a)(.*?)(?= %)"),"^\\[|\\]$")) %>% 
  left_join(nodegoat_institutions %>% select(Project_ID_institution=Project_ID,Entity_Name,Located_Location) %>% cSplit(.,"Entity_Name",sep = "|",direction = "long"),by = c("Creator"="Entity_Name","X210"="Located_Location")) %>%  
  left_join(nodegoat_institutions %>% select(Project_ID_institution2=Project_ID,Entity_Name) %>% cSplit(.,"Entity_Name",sep = "|",direction = "long"),by = c("Creator"="Entity_Name")) %>% 
  mutate(Project_ID_institution = ifelse(!is.na(Project_ID_institution),paste3(Project_ID_institution),
                                         ifelse(is.na(Project_ID_institution)&!is.na(Project_ID_institution2),paste3(Project_ID_institution2),NA))) %>% 
  mutate(Creator = ifelse(is.na(Creator),NA,paste3(Project_ID_institution))) %>% 
  select(-X210,-Project_ID_institution2,-nr_zapisu,-Project_ID_institution) %>% 
  group_by(group_id) %>% 
  mutate(Series_Title = paste(unique(na.omit(Series_Title)),collapse = "|"),
         Addition_to_Title = paste(unique(na.omit(Addition_to_Title)),collapse = "|"),
         Creator = str_replace(paste(unique(na.omit(Creator)),collapse = "|"),"(^.*?)(\\|.*$)","\\1"),
         Sub_Series = paste(unique(na.omit(Sub_Series)),collapse = "|"),
         Main_Series = paste(unique(na.omit(Main_Series)),collapse = "|"),
         group = paste(unique(na.omit(group)),collapse = "|")) %>% 
  ungroup() %>% 
  unique() %>% 
  mutate(Project_ID = 1:n())
  
write.csv2(nodegoat_series, file = "C:/Users/Cezary/Desktop/nodegoat_series.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

```


```{r}
bn_people_record_id_X701 <- bn_people_record_id_X701 %>%
  group_by(name_total) %>%
  mutate(record_id_group = paste(record_id,collapse = "|")) %>%
  mutate(record_id_group = paste("bn_X701",record_id_group,sep = "|")) %>%
  ungroup() %>%
  select(last_name,first_name,years,name_total,record_id_group) %>%
  unique()

#concatenate all bn
bn_people_record_id <- rbind(bn_people_record_id_X100,bn_people_record_id_X700,bn_people_record_id_X701)
bn_people_record_id <- bn_people_record_id %>%
  group_by(name_total) %>%
  mutate(record_id_group = paste(record_id_group,collapse = "~")) %>%
  ungroup() %>%
  mutate(person_id = paste("bn_b_",seq.int(nrow(bn_people_record_id)),sep = "")) %>%
  select(person_id,1:5)
```


