---
title: "R Notebook"
output: html_notebook
---

```{r}

#biblioteki
options(java.parameters = "-Xmx32000m")
options(scipen = 999)
pacman::p_load(utf8,googlesheets4,zoo,stringr,splitstackshape,plyr,dplyr,sqldf,stringdist,fuzzyjoin,data.table,svMisc,tidyverse,RJDBC,openxlsx,jsonlite,reshape2,RSelenium,XML,methods,xml2)
`%notin%` <- Negate(`%in%`)

#reading cz authority file and processing to table
cz_authorities <- readLines("C:/Users/Cezary/Downloads/CLOselection.txt", encoding = "UTF-8")

cz_authorities <- data.frame(cz_authorities) %>% 
  mutate(cz_authorities = ifelse(grepl("       ",cz_authorities),str_replace(cz_authorities,"       "," AAA   "),as.character(cz_authorities)))
cz_authorities <- cz_authorities %>% 
  mutate(id = as.character(str_extract_all(cz_authorities, "^\\d{9}")),
         field = str_replace_all(cz_authorities, "(\\d{9} )(\\w{3})(.*)", "\\2"),
         content = str_replace_all(str_replace_all(cz_authorities,"(\\d{9} )(\\w{3})(\\s{3})(.*)","\\1\\2 \\4"),"(\\d{9} )(\\w{3})(\\d\\s|\\d\\d|\\s\\d){0,2}( L )(.*)","\\3\\5"),
         id_field = paste(id,field,sep = "|"))
count <- cz_authorities %>%
  select(5,1)
count <- as.data.frame(table(count$id_field))
data1 <- cz_authorities %>% 
  left_join(count,by=c("id_field"="Var1"))
remove(count)

data1_to_join <- data1 %>%
  filter(Freq > 1) %>% 
  group_by(id_field) %>% 
  mutate(content = paste(content, collapse = "|")) %>% 
  ungroup() %>% 
  unique() %>% 
  mutate(id = str_replace_all(id_field,"(\\d{9})(\\|)(.*)", "\\1"),
         field = str_replace_all(id_field,"(\\d{9})(\\|)(.*)", "\\3")) %>% 
  select(-Freq)

data1 <- data1 %>%
  filter(id_field %notin% data1_to_join$id_field) %>% 
  bind_rows(data1_to_join) %>% 
  arrange(id_field,field) %>% 
  select(2,3,4) %>% 
  mutate(field = paste("X",field,sep = ""))
remove(data1_to_join)

f.agg <- function(x) paste(unique(x), collapse = "~")
data_table <- dcast(data1, id ~ field, value.var="content", fun.aggregate = f.agg)

#extracting value with name from the field no. 100
marc_field_100 <- data_table %>%
  select(X001,X100)%>%
  filter(X100!="") %>% 
  mutate(X100 = str_replace_all(X100,"(^|\\|)","~\\1")) %>% 
  cSplit("X100",sep = "~",direction = "long") %>% 
  filter(X100!="") %>% 
  mutate(X100 = str_remove_all(X100,"^\\|"),
         indicator = str_replace_all(X100,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(data_table$X100,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field_100)[1]))
colnames(empty_table) <-subfield_list

marc_field_100<-cbind(marc_field_100,empty_table)

subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")

x <- 1:length(subfield_list)

for (i in x) {
  marc_field_100$X100 <- str_replace(marc_field_100$X100,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field_100[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field_100$X100),str_replace_all(gsub(string,"\\3",marc_field_100$X100),"\\${2}.", "~"),NA)
}

#dropped
# dropped <- marc_field_100 %>% 
#   filter(is.na(`$$7`))
# 
# write.xlsx(dropped, "C:/Users/Cezary/Desktop/dropped.xlsx")
# 
# dates <- marc_field_100 %>% 
#   filter(!is.na(`$$d`))

#extracting all local id from VIAF
marc_field_100 <- marc_field_100 %>% 
  filter(!is.na(`$$7`)|!is.na(`$$d`))

rD <- rsDriver(port=4444L,browser="chrome", chromever="79.0.3945.36")
remDr <- rD$client

x <- 1:nrow(marc_field_100)
cz_viaf_ids <- data.frame(stringsAsFactors = FALSE)
for (i in x) {
  progress(match(i,x), max.value = length(x))
  if (!is.na(marc_field_100$`$$7`[i])) {
    url <- paste("http://viaf.org/viaf/sourceID/NKC%7C",marc_field_100$`$$7`[i],sep = "")
  remDr$navigate(url)
  viaf_id <- str_replace(as.character(remDr$getCurrentUrl()),"https","http")
  xml <- xmlParse(paste(viaf_id,"viaf.xml",sep = ""))
  tryCatch({
    IDs <- setNames(xmlToDataFrame(nodes = getNodeSet(xml, "//ns1:VIAFCluster/ns1:mainHeadings/ns1:data/ns1:sources/ns1:sid")),"IDs")
    IDs <- paste(unlist(IDs), collapse = "~")
    }, error=function(e){
      IDs <<- "Brak danych (CR)"
      })
  tryCatch({
  nationality <- setNames(xmlToDataFrame(nodes = getNodeSet(xml, "//ns1:VIAFCluster/ns1:nationalityOfEntity/ns1:data/ns1:text")),"Nationality")
  nationality <- paste(unlist(nationality), collapse = "~")
  }, error=function(e){
    nationality <<- "Brak danych (CR)"
    })
  tryCatch({
  language <- setNames(xmlToDataFrame(nodes = getNodeSet(xml, "//ns1:VIAFCluster/ns1:languageOfEntity/ns1:data/ns1:text")),"Language")
  language <- paste(unlist(language), collapse = "~")
  }, error=function(e){
    language <<- "Brak danych (CR)"
    })
  iteration <- cbind(cz_name=marc_field_100$`$$a`[i],viaf_id,IDs,nationality,language)
  cz_viaf_ids <- rbind(cz_viaf_ids,iteration)
    
  } else {
    url <- paste("http://viaf.org/viaf/search?query=local.personalNames%20all%20%22",str_replace_all(paste(marc_field_100$`$$a`[i],marc_field_100$`$$d`[i],sep = " ")," ","%20"),"%22%20and%20local.sources%20any%20%22nkc%22&sortKeys=holdingscount&recordSchema=BriefVIAF",sep = "")
    remDr$navigate(url)
    tryCatch({
    enter <- remDr$findElement(using = 'css selector', "div.inner table:nth-child(2) tbody:nth-child(1) tr:nth-child(2) td.recName > a:nth-child(1)")
    enter$clickElement()
    viaf_id <- str_remove(str_replace(as.character(remDr$getCurrentUrl()),"https","http"),"\\#.*$")
  xml <- xmlParse(paste(viaf_id,"viaf.xml",sep = ""))
  tryCatch({
    IDs <- setNames(xmlToDataFrame(nodes = getNodeSet(xml, "//ns1:VIAFCluster/ns1:mainHeadings/ns1:data/ns1:sources/ns1:sid")),"IDs")
    IDs <- paste(unlist(IDs), collapse = "~")
    }, error=function(e){
      IDs <<- "Brak danych (CR)"
      })
  tryCatch({
  nationality <- setNames(xmlToDataFrame(nodes = getNodeSet(xml, "//ns1:VIAFCluster/ns1:nationalityOfEntity/ns1:data/ns1:text")),"Nationality")
  nationality <- paste(unlist(nationality), collapse = "~")
  }, error=function(e){
    nationality <<- "Brak danych (CR)"
    })
  tryCatch({
  language <- setNames(xmlToDataFrame(nodes = getNodeSet(xml, "//ns1:VIAFCluster/ns1:languageOfEntity/ns1:data/ns1:text")),"Language")
  language <- paste(unlist(language), collapse = "~")
  }, error=function(e){
    language <<- "Brak danych (CR)"
    })
    
    }, error=function(e){
      viaf_id <<- "Brak danych (CR)"
      IDs <<- "Brak danych (CR)"
      nationality <<- "Brak danych (CR)"
      language <<- "Brak danych (CR)"
    })
      iteration <- cbind(cz_name=marc_field_100$`$$a`[i],viaf_id,IDs,nationality,language)
      cz_viaf_ids <- rbind(cz_viaf_ids,iteration)
  }
}


cz_viaf_ids_long <- cz_viaf_ids %>% 
  cSplit("IDs",sep = "~",direction = "long")

#write.xlsx(cz_viaf_ids_long, "C:/Users/Cezary/Desktop/cz_viaf_ids_long.xlsx")

# selection of national libraries: Polish: PLWABN, Swedish: SELIBR

pl_swe_viaf <- cz_viaf_ids_long %>% 
  filter(grepl("PLWABN|SELIBR",IDs)) %>% 
  select(name=cz_name,viaf_id) %>% 
  unique() %>% 
  arrange(name) %>% 
  mutate(in_polish = TRUE,
         in_swedish = TRUE)

#downloading all person's name forms from selected libraries

x <- 1:nrow(pl_swe_viaf)
full_data_pl_swe <- data.frame(stringsAsFactors = FALSE)
for (i in x) {
  progress(match(i,x), max.value = length(x))
  url <- paste(pl_swe_viaf$viaf_id[i],"viaf.xml",sep = "")
  xml <- read_xml(url)
  baz <- xml_find_all(xml,".//ns1:x400s/ns1:x400/ns1:datafield/ns1:subfield")
  test <- baz %>% xml_attr("code")
  test2 <- xml_text(baz)
  baz2 <- xml_find_all(xml,".//ns1:x400s/ns1:x400/ns1:sources")
  test3 <- data.frame(test3 = xml_text(baz2))
  test <- data.frame(test,test2) %>% 
    filter(test=="a",
           !grepl("\\:$",test2)) %>% 
    mutate(test2 = as.character(test2)) %>% 
    bind_cols(test3 %>% mutate(test3 = as.character(test3))) %>% 
    filter(grepl("PLWABN|SELIBR",test3)) %>% 
    mutate(in_polish = ifelse(grepl("PLWABN",test3),TRUE,FALSE),
           in_swedish = ifelse(grepl("SELIBR",test3),TRUE,FALSE),
           viaf_id = pl_swe_viaf$viaf_id[i]) %>% 
    select(name = test2,in_polish,in_swedish,viaf_id)
  iteration <- pl_swe_viaf[i,] %>% 
    bind_rows(test)
  full_data_pl_swe <- rbind(full_data_pl_swe,iteration)
}

#write.xlsx(full_data_pl_swe, "C:/Users/Cezary/Desktop/full_data_pl_swe.xlsx")
```

```{r Swedish}
swedish_data <- full_data_pl_swe %>% 
  filter(in_swedish==T) %>% 
  select(1,2)
f.agg <- function(x) paste(unique(x), collapse = "~")
#queries in Swedish library

x <- 1:nrow(swedish_data)
data_full <- data.frame(stringsAsFactors = FALSE)
for (i in x) {
  progress(match(i,x), max.value = length(x))
  url <- paste("http://libris.kb.se/xsearch?query=forf:(",str_replace_all(swedish_data$name[i]," ","%20"),")&start=1&n=200&format=marcxml&format_level=full",sep = "")
  
  tryCatch({

  doc <- read_xml(url)
  
  node <- xml_find_all(doc, "//xsearch")
  node_att <- xml_attr(node, "records")
  if (node_att>0) {
    
  b <- 1:as.integer(node_att)
  b <- split(b, ceiling(seq_along(b)/200))
  b <- as.integer(lapply(b, `[[`, 1))
for (a in b) {
  url <- paste("http://libris.kb.se/xsearch?query=forf:(",str_replace_all(swedish_data$name[i]," ","%20"),")&start=",a,"&n=200&format=marcxml&format_level=full",sep = "")
  
  nodes <- xml_find_all(doc, ".//marc:record")
  nodes_controlfield <- xml_find_all(doc, ".//marc:record/marc:controlfield")
  nodenum_controlfield <- xml_attr(nodes_controlfield, "tag")
  nodes_datafield <- xml_find_all(doc, ".//marc:record/marc:datafield")
  nodenum_datafield <- xml_attr(nodes_datafield, "tag")
  nodes_subfield <- xml_find_all(doc, ".//marc:record/marc:datafield/marc:subfield")
  nodenum_subfield <- xml_attr(nodes_subfield, "code")
  nodeslength<-xml_length(nodes)
  nodeslength2<-xml_length(nodes_datafield)
  nodenames<-xml_name(xml_children(nodes))
  nodenames_datafield<-xml_name(xml_children(nodes_datafield))
  nodevalues<-trimws(xml_text(xml_children(nodes)))
  nodevalues2<-trimws(xml_text(xml_children(nodes_datafield)))
  nodenum_controlfield <- data.frame(nodenum = nodenum_controlfield) %>% 
    mutate(nodenames = paste("controlfield",seq(1:n()),sep = ""),
           nodenum = as.character(nodenum))
  nodenum_datafield <- data.frame(nodenum = nodenum_datafield) %>% 
    mutate(nodenames = paste("datafield",seq(1:n()),sep = ""),
           nodenum = as.character(nodenum))
  test <- data.frame(nodenames = nodenames) %>% 
    bind_cols(nodevalues = nodevalues) %>% 
    group_by(nodenames) %>% 
    mutate(seq=1:n()) %>% 
    ungroup() %>% 
    unite("nodenames", c(nodenames,seq), sep = "") %>% 
    left_join(bind_rows(nodenum_controlfield,nodenum_datafield),by="nodenames") %>% 
    mutate(nodenum = ifelse(is.na(nodenum),"LDR",as.character(nodenum)))
  test2 <- data.frame(nodeslength2) %>% 
    mutate(nodenames = paste("datafield",seq(1:n()),sep = ""))
  test <- test %>% 
    left_join(test2,by="nodenames")
  test <- test %>% 
    mutate(nodeslength2 = ifelse(!is.na(nodeslength2),as.integer(nodeslength2),0))
  y <- 1:nrow(test)
  for (j in y) {
    test$nodenames2[j] <- ifelse(test$nodeslength2[j]>0,paste("subfield",paste(replicate(test$nodeslength2[j],"|"),collapse = ""),sep = ""),NA)
  }
  deeper_nodes<- data.frame(nodenames = nodenames_datafield) %>% 
    bind_cols(nodenums = nodenum_subfield) %>% 
    bind_cols(nodevalue = nodevalues2) %>% 
    mutate(seq=1:n()) %>% 
    unite("nodenames", c(nodenames,seq), sep = "")
  testowy <- test %>% 
    cSplit("nodenames2",sep = "|",direction = "long") %>% 
    mutate(nodenames = str_remove(nodenames,"\\d+$")) %>% 
    group_by(nodenames) %>% 
    mutate(nodenames2 = ifelse(nodenames=="datafield",paste("subfield",seq(1:n()),sep = ""),NA)) %>% 
    ungroup() %>% 
    left_join(deeper_nodes,by = c("nodenames2"="nodenames"))
  testowy2 <- testowy %>% 
    mutate(content = ifelse(!is.na(nodevalue),paste("$",as.character(nodenums),as.character(nodevalue),sep = ""),as.character(nodevalues))) %>%
    mutate(record_group = ifelse(nodenum=="LDR",seq(1:n()),NA)) %>%
    fill(record_group) %>%
    mutate(id = ifelse(nodenum=="001",as.character(content),NA)) %>%
    group_by(record_group) %>%
    fill(id,.direction = "downup") %>%
    ungroup() %>%
    select(id,field=nodenum,content) %>% 
    mutate(id_field = paste(id,field,sep = "|"))
  if (nrow(testowy2)>0) {
    count <- testowy2 %>%
      select(4,3)
    count <- as.data.frame(table(count$id_field))
    data1 <- testowy2 %>%
      left_join(count %>% mutate(Var1 = as.character(Var1)),by=c("id_field"="Var1"))
    data1_to_join <- data1 %>%
      filter(Freq > 1) %>%
      group_by(id_field) %>%
      mutate(content = paste(content, collapse="|")) %>%
      ungroup() %>%
      unique() %>%
      mutate(id = str_replace_all(id_field,"(.*)(\\|)(.*)", "\\1"),
             field = str_replace_all(id_field,"(.*)(\\|)(.*)", "\\3")) %>%
      select(-Freq)
    data1 <- data1 %>%
      filter(id_field %notin% data1_to_join$id_field) %>%
      bind_rows(.,data1_to_join) %>%
      arrange(id_field,field) %>%
      select(1,2,3) %>% 
      mutate(field = ifelse(field=="LDR","LDR~~",as.character(field)),
             content = ifelse(field=="LDR~~",paste(content,"~~",sep = ""),as.character(content))) %>% 
      cSplit(c("field","content"),sep = "~",direction = "long") %>% 
      mutate(field = ifelse(field=="","viaf",as.character(field)),
             content = ifelse(content=="",paste(swedish_data$name[i],viaf_id = swedish_data$viaf_id[i],sep = "|"),as.character(content)))
    remove(data1_to_join)
    data_full <- data_full %>%
      bind_rows(.,data1)
  } 
}
  }
  }, error=function(e){
      })
}

data_full_wide <- dcast(data_full, id ~ field, value.var="content", fun.aggregate = f.agg) %>% 
  cSplit("viaf",sep = "~",direction = "long")
#write.xlsx(data_full_wide, "C:/Users/Cezary/Desktop/data_full_wide.xlsx")

#nie ma pola 041, w 008 są śmieci, wyczyścić listę nazwisk dopasowaniem dokładnym

#dopasowanie dokładne

x <- 1:nrow(data_full_wide)
for (i in x) {
  progress(match(i,x), max.value = length(x))
  data_full_wide$person_match[i] <- ifelse(grepl(str_replace(data_full_wide$viaf[i],"(^.*?)(\\|.*$)","\\1"),data_full_wide$`100`[i]),TRUE,FALSE)
}

dobre <- data_full_wide %>% 
  filter(person_match==TRUE) %>% 
  select(-NA,-person_match) %>% 
  mutate(viaf = str_replace(viaf,"(^.*\\|)(.*?$)","\\2")) %>% 
  unique()
write.xlsx(dobre, "C:/Users/Cezary/Desktop/dobre_szwedzkie.xlsx")



```


